apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage1
  labels: 
    component: backstage-workloads
  annotations:
    backstage.io/kubernetes-id: test-backstage1
    janus-idp.io/tekton-enabled: 'true'
    #dev.azure.com/project-repo: my-project/my-repo
spec:
  type: service
  lifecycle: unknown
  owner: temp-d
