apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: my-backstage
  labels: 
    component: backstage-workloads
  annotations:
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/kubernetes-id: my-backstage
    janus-idp.io/tekton-enabled: 'true'
    janus-idp.io/tekton: my-backstage
    #dev.azure.com/project-repo: my-project/my-repo
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: janus-idp/backstage-showcase
    'jfrog-artifactory/image-name': 'test'
    nexus-repository-manager/docker.image-name: sonatype/nexus3
spec:
  type: service
  lifecycle: unknown
  owner: Debsmita
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: my-team
  description: Debsmita's Team
spec:
  type: team
  profile:
    displayName: Debsmita's Team
    email: team-c@example.com
    picture: https://api.dicebear.com/7.x/identicon/svg?seed=Loki&backgroundType=gradientLinear&backgroundColor=b6e3f4,ffd5dc,ffdfbf,c0aede
  parent: boxoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: debsmita1
spec:
  profile:
    displayName: Debsmita Santra
    email: dsantra@redhat.com
    picture: https://api.dicebear.com/7.x/avataaars/svg?seed=Bear&backgroundColor=transparent
  memberOf: [my-team]
