apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: nodejs-backstage
  labels: 
    component: backstage-workloads
  annotations:
    quay.io/repository-slug: janus-idp/backstage-showcase
    backstage.io/kubernetes-id: nodejs-backstage
    backstage.io/kubernetes-label-selector: 'backstage-component in (test-backstage)'
    janus-idp.io/tekton-enabled: 'true'
    #dev.azure.com/project-repo: my-project/my-repo
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: janus-idp/backstage-showcase
    backstage.io/techdocs-ref: dir:.
    'jfrog-artifactory/image-name': 'test'
    nexus-repository-manager/docker.image-name: sonatype/nexus3
spec:
  type: service
  lifecycle: unknown
  owner: Debsmita
