apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test-backstage
  labels: 
    component: backstage-workloads
  annotations:
    github.com/project-slug: debsmita1/nodejs-ex-1
    backstage.io/kubernetes-id: openshift-cluster
    backstage.io/kubernetes-namespace: deb-test
spec:
  type: service
  lifecycle: unknown
  owner: temp-d
